# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02672dd864aece56310df075154c65a9268e92649ae0b6428425510cc651252d62ec8db7a54276f5c76657c26fe90f4a507458967816b2cf83fbe7fafc86e27f

test:
  secret_key_base: 6e8b226186ab01ff624a17e49dc749f6d83add0104a44c304998b85be7cc542a08e758d169c71501b5256eb61bd942ba46221692b1ebf56795b422e3fb1ef3c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
